-- SELECT * FROM classicmodels.employees;

-- SELECT * FROM classicmodels.employees;
-- SELECT * FROM employees;
-- SELECT * FROM customers;
-- select * from employees where jobTitle = "sales Rep" and   employeeNumber between 1200 and 1500;
-- select * from employees where officeCode >= 2 and jobTitle != "sales Rep";
-- select * from customers where country != "USA"; 
-- select * from customers where customerNumber not between 150 and 200;
-- select firstName,lastName as "Name of the employee" from employees order by lastName;
-- select * from customers where creditLimit > 70000 order by contactLastName desc; 
-- select * from customers where city in ("singapore","Liverpool","NYC");
-- select * from customers where contactLastName like "smith%";
-- select * from employees where officeCode in (1,3,5);
-- select * from customers where creditLimit between 50000 and 95000; 
-- select * from employees where officeCode not in (1,3);
-- select * from customers where customerName like "s%";
-- select * from customers where contactLastName like "s%h";
-- select * from customers where contactFirstName like "s____%";
-- select * from customers where length(contactFirstName) = 8 ;
-- select * from customers where customerName like 'a%e';
-- select * from customers where customerName like '%ee%';
-- select jobtitle , count(*) from employees group by jobTitle;
-- select state, max(creditLimit) from customers group by state;

